name: Security Testing

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]



jobs:
  security-testing:
    name: security-testing
    uses: affinidi-appSec-test/pipeline-security/.github/workflows/security-scanners.yml@feat-sonarcloud
    secrets: 
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
