name: Security Testing

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]



jobs:
  security-testing:
    name: security-testing
    uses: Affinidi-AppSec-Test/pipeline-security/.github/workflows/security-scanners.yml@main
    secrets: 
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
